Repository causticsudo/servicebus-lifeboat, pull requests merged in 2023-05, with the labels that each got.

#2 :recycle: refactor: migrate application to cli
  .gitignore
  ServiceBusLifeboat.sln
  src/ServiceBusLifeboat.Cli/Program.cs
  src/ServiceBusLifeboat.Cli/ServiceBusLifeboat.Cli.csproj
  src/ServiceBusLifeboat.Cli/sample.md
  src/ServiceBusLifeboat.Console/Program.cs
  src/ServiceBusLifeboat.Console/ServiceBusLifeboat.Console.csproj
  src/ServiceBusLifeboat.Domain/Class1.cs
  src/ServiceBusLifeboat.Domain/ServiceBusLifeboat.Domain.csproj
Labels: enhancement

#3 💚 requirement: add action
  .github/GitVersion.yml
  .github/workflows/build-publish.yml
  .github/workflows/cd-release.yml
  .github/workflows/ci-build.yml
  README.md
  tests/ServiceBusLifeboat.UnitTests/ServiceBusLifeboat.UnitTests.csproj
Labels: requirement

#8 👷 build: fix application cd
  .github/workflows/cd-release.yml
Labels: bug

#9 :construction_worker: build: fix github token
  .github/workflows/cd-release.yml
Labels: bug

#10 💚 fix: pipeline cd
  .github/workflows/cd-release.yml
Labels: bug

#11 Fix/pipeline cd
  .github/workflows/cd-release.yml
  .github/workflows/ci-build.yml
  tests/ServiceBusLifeboat.UnitTests/ServiceBusLifeboat.UnitTests.csproj
Labels: bug

#12 Fix/pipeline cd
  .github/workflows/cd-release.yml
  .github/workflows/ci-build.yml
Labels: bug
